# Generated by Django 5.1.15 on 2026-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0003_evidence_file_alter_evidence_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="quote",
            name="payment_plan",
            field=models.CharField(
                blank=True,
                choices=[("full", "Full Payment"), ("fifty_fifty", "50/50 Deposit")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issued"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("superseded", "Superseded"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                ],
                max_length=50,
            ),
        ),
    ]
