# Generated by Django 5.1.15 on 2026-08-28 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0004_quote_amount_paid_quote_payment_plan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("site_observations", models.TextField(blank=True, null=True)),
                ("required_materials", models.TextField(blank=True, null=True)),
                ("required_tools", models.TextField(blank=True, null=True)),
                ("installation_notes", models.TextField(blank=True, null=True)),
                ("recommendations", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_report",
                        to="requests.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Report",
                "verbose_name_plural": "Inspection Reports",
            },
        ),
        migrations.CreateModel(
            name="InspectionPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_url", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="inspection_photos/"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="requests.inspectionreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Photo",
                "verbose_name_plural": "Inspection Photos",
            },
        ),
    ]
