# Generated by Django 5.1.15 on 2026-08-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("payments", "0002_alter_payment_status"),
        ("requests", "0004_quote_amount_paid_quote_payment_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="requests.quote",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="orders.order",
            ),
        ),
    ]
